### ISSUE TITLE
Does the OPML Editor run on Mojave?

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#98]
Here's where you download the latest [OPML Editor](http://home.opml.org/#1506805469000) release for MacOS.

1. At some point I am told the software will not work on the current release of Mac OS.

2. I want to buy a new iMac Pro, basically the last Mac I buy for my own use, because the OPML Editor is a critical tool in my software development kit. I use it to write and deploy my code.

3. I would really rather be using Linux for all my work, and hopefully at some point I will be able to, but the OPML Editor hasn't been ported to Linux yet.

So if you have a Mac running Mojave, could you try the OPML Editor, and let me know if it works. 

Thanks, hopefully it does run, I would like to get a new desktop machine. :-)

Dave

**Comment by facej** [comment]
Can't get the download to work on any of my Macs - 10.12, 10.13, or 10.14
NB I have a copy of OPML on my 10.12 machine. The last time I actually ran the application appears to be 2013.

I have tried "all the tricks" to get OPML to run on Mojave. It has gotten as far as the dialog asking where the opml.root database is, but it won't let me choose the location that contains the .root file.

When I run from the shell on Mojave I see the following error messages which may be quite telling...

`/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
dyld: lazy symbol binding failed: Symbol not found: _OTLIFOStealList
  Referenced from: /Users/myname/Apps/OPML/./OPML.app/Contents/MacOS/OPML
  Expected in: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices

dyld: Symbol not found: _OTLIFOStealList
  Referenced from: /Users/chrisjanton/Apps/OPML/./OPML.app/Contents/MacOS/OPML
  Expected in: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices

Abort trap: 6
`
I can't get it to run on High Sierra, or Sierra either. Attempt on Sierra (from the command line) gave me

`face@sMac:OPML:121 $ ./OPML.app/Contents/MacOS/OPML 
dyld: lazy symbol binding failed: Symbol not found: _OTLIFOStealList
  Referenced from: /Users/x/Downloads/OPML/./OPML.app/Contents/MacOS/OPML
  Expected in: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices

dyld: Symbol not found: _OTLIFOStealList
  Referenced from: /Users/x/Downloads/OPML/./OPML.app/Contents/MacOS/OPML
  Expected in: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices

Abort trap: 6
x@sMac:OPML:122 $ 
`

**Comment by scripting** [comment]
@facej -- this is a documented problem. I should include a link to the workaround on the download page. Here it is -- 

https://github.com/tedchoward/Frontier/issues/9

**Comment by facej** [comment]
Short answer is - it looks like Mojave is just fine given proper care and feeding. I suspect that giving OPML "full filesystem access" might be a handy thing to do - I did that on GPs.

Pretty cool - my 20+ year old code seems to look just fine ;-)

What I really needed was a link to the proper download for the version of OPML that comes from the reference "OPML-full-distribution.dmg". Try finding that ;-)

What I eventually did was to stumble my way to this link

  https://github.com/tedchoward/Frontier/releases/tag/10.2d4

I took that version of the application and started it up (control-click on the application in Finder, choose "Open" to allow it to run un-signed application)

I have the "About OPML" window displaying the time and threads on my Mojave machine.

As I wander through config.root things appear to be OK, with display oddness that I recall from a long time ago.

I haven't done any Frontier/OPML in a very long time. Is there anything that you want me to try specifically? I can create an outline and render it in the browser. 

I didn't have to do any of the workaround things...

NB - my 1999 live database application still opens and lets me view the web pages - clearly the hooks to ODBC and JDBC fail, but the whole environment seems just fine...

**Comment by prk60091** [comment]
MacBook Pro (Retina, 13-inch, Early 2015)
MacOs 10.14 (18A390)
downloaded OPML  works fine after granting permission to run (System Pref->Security & Privacy->General->Allow App from developer

**Comment by scripting** [comment]
I got enough confirmation that the OPML Editor runs on Mojave, so I went ahead and bought the iMac Pro. Blog post is here. 

http://scripting.com/2018/10/22.html#a132351

**Comment by scripting** [comment]
The consensus is that the OPML Editor does run on Mojave, so I went ahead and bought an iMac Pro. 

This should be my last Mac purchase, assuming things go as I think they will (you never know).

http://scripting.com/2018/10/22.html#a132351
